name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Compile
        run: make
      - name: Install test framework
        run: make -C tests install
      - name: Unit Test
        run: make -C tests
      - name: Get Version
        id: get_version
        run: echo "VERSION=$(cat build/version.txt)" >> $GITHUB_ENV
      - name: Create Release
        run: |
          gh release create ${{ env.VERSION }} \
            --title "${{ env.VERSION }}" \
            --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
