name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Compile
        run: make
      - name: Install test framework
        run: make -C tests install
      - name: Unit Test
        run: make -C tests
      - name: Get Version
        id: get_version
        run: echo "::set-output name=VERSION::$(cat build/version.txt)"
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: ${{ steps.get_version.outputs.VERSION }}
          body: |
            ${{ steps.get_version.outputs.VERSION }}

            ## Features
            ## Bug Fixes
          draft: false
          prerelease: false
